[book]
title = "Plist Manager"
description = "Nix-Based macOS User Defaults Done Right"
language = "en"
multilingual = false
src = "src"

[output.html]
site-url = "/plist-manager/"
git-repository-url = "https://github.com/z0al/plist-manager"

[preprocessor.toc]
command = "mdbook-toc"
max-level = 3
renderer = ["html"]
