[book]
title = "Plist-manager"
description = "Nix-Based macOS User Defaults Done Right"
language = "en"
multilingual = false
src = "src"

[output.html]
site-url = "/plist-manager/"
default-theme = "latte"
preferred-dark-theme = "mocha"
additional-css = ["./theme/catppuccin.css", "./theme/custom.css"]
git-repository-url = "https://github.com/z0al/plist-manager"

[preprocessor.toc]
command = "mdbook-toc"
max-level = 3
renderer = ["html"]

[preprocessor.alerts]
