[book]
title = "Better Darwin Defaults"
description = "Declarative & human-friendly darwin user defaults"

[output.html]
site-url = "/better-defaults.nix/"
git-repository-url = "https://github.com/z0al/better-defaults.nix"
edit-url-template = "https://github.com/z0al/better-defaults.nix/edit/master/docs/{path}"
