[book]
title = "Better Darwin Defaults"
description = "Declarative & human-friendly darwin user defaults"

[output.html]
site-url = "/plist-manager/"
git-repository-url = "https://github.com/z0al/plist-manager"
edit-url-template = "https://github.com/z0al/plist-manager/edit/master/docs/{path}"
