[book]
title = "Darwin Defaults"
description = "Declarative & human-friendly darwin user defaults"

[output.html]
site-url = "/defaults.nix/"
git-repository-url = "https://github.com/z0al/defaults.nix"
edit-url-template = "https://github.com/z0al/defaults.nix/edit/master/docs/{path}"
