name: "Test"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - run: nix flake check
